name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17 (or any other version you need)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Download JUnit JAR file
      - name: Download JUnit
        run: curl -L -o junit.jar https://search.maven.org/remotecontent?filepath=junit/junit/4.13.2/junit-4.13.2.jar

      # Step 4: Download Hamcrest (required by JUnit)
      - name: Download Hamcrest
        run: curl -L -o hamcrest.jar https://search.maven.org/remotecontent?filepath=org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar

      # Step 5: Compile the Java files (source and test files)
      - name: Compile Java files with JUnit
        run: javac -cp .:junit.jar:hamcrest.jar -d out src/*.java tests/*.java

      # Step 6: Run the JUnit tests
      - name: Run JUnit Tests
        # JUnit expects to run the tests from compiled .class files, not the .java files
        run: java -cp out:junit.jar:hamcrest.jar org.junit.runner.JUnitCore tests.*
