name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK (choose your desired version)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Compile Java files manually
      - name: Compile Java files
        run: javac -d out src/*.java

      # Run tests manually
      - name: Run Tests
        run: java -cp out:./lib/* org.junit.runner.JUnitCore tests/*.java
